policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d/
    values:
      - updatecli/values.d/scm.yaml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/updatecli-compose.yaml
  - name: Rust
    policy: ghcr.io/updatecli/policies/autodiscovery/cargo:0.9.1@sha256:237c49b0541ad1a5ce9bcdfef0a525dd47ff854436dee61985b56f2c981c828d
    values:
      - updatecli/values.d/scm.yaml
  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1@sha256:869b676074f9fee7edd5d488140a12c3b09a5f8a175f12f26ea85a4f8bd0a9d1
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/digest.yaml
      - updatecli/values.d/githubactions.yaml
  - name: Update precommit
    policy: ghcr.io/updatecli/policies/autodiscovery/precommit:0.3.0@sha256:73b4e3ef11538afa83d12f25a642d574407e4f04703beb22ef5f6111e641d386
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/digest.yaml
