name: updatecli
on:
  release: null
  workflow_dispatch: null
  push:
    branches: [main]
  schedule:
    # Run every day
    - cron: "0 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@7301666af81042d5d099dde07427e26ff2087bf1" # v2
      - name: "Run updatecli"
        run: "updatecli compose ${{ github.ref == 'refs/heads/main' && 'apply --clean-git-branches' || 'diff' }}"
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.LOIS_BOT_APP_ID }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: ${{ secrets.LOIS_BOT_APP_INSTALLATION_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.LOIS_BOT_PRIVATE_KEY }}
